# Generated by Django 3.2.8 on 2021-10-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('section_objects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='object_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
