# Generated by Django 3.2.8 on 2021-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=50)),
                ('filter_type', models.CharField(choices=[('RNG', 'Диапазон значений'), ('MUL', 'Множественный выбор'), ('SNGL', 'Единичный выбор')], default='RNG', max_length=30)),
            ],
            options={
                'verbose_name': 'Фильтр раздела',
                'verbose_name_plural': 'Фильтры раздела',
            },
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_objects',
        ),
    ]
