# Generated by Django 3.2.8 on 2021-10-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211017_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfilter',
            name='filter_section',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
