# Generated by Django 3.2.8 on 2021-10-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211017_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='object_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Раздел объекта'),
        ),
        migrations.AlterField(
            model_name='objectattribute',
            name='attibute_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.sectionfilter', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='objectattribute',
            name='parent_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='sectionfilter',
            name='filter_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Раздел, в котором будет доступен фильтр'),
        ),
    ]
