# Generated by Django 3.2.8 on 2021-10-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_objectattribute_parent_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectattribute',
            name='parent_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='Объект'),
        ),
    ]
