# Generated by Django 3.2.8 on 2021-10-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_objectattribute_parent_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectattribute',
            old_name='attibute_type',
            new_name='atrtibute_type',
        ),
    ]
