# Generated by Django 3.2.8 on 2021-10-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_attibute_type_objectattribute_atrtibute_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectattribute',
            old_name='atrtibute_type',
            new_name='attribute_type',
        ),
    ]
