# Generated by Django 3.2.8 on 2021-10-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_atrtibute_type_objectattribute_attribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
